[package]
name = "helixer_post_bin"
version = "0.1.0"
authors = ["Tony Bolger <bolger.tony@gmail.com>"]
edition = "2018"

[dependencies]
hdf5 = "0.8.1"
ndarray = "0.15.6"

[dev-dependencies]
predicates = "2"
assert_cmd = "2"